// src/vue/StackedPlot.vue
<script setup lang="ts">
import { useStackedPlot, type UseStackedPlotOptions } from "./useStackedPlot";

const props = withDefaults(
  defineProps<
    UseStackedPlotOptions & {
      width?: number | string;
      height?: number | string;
      class?: string;
      ariaLabel?: string;
    }
  >(),
  {
    width: "100%",
    height: 480,
  },
);

const { containerRef, stack, isReady, fitAll, resetAll } = useStackedPlot(props);

defineExpose({
  getStack: () => stack.value,
  fitAll,
  resetAll,
  getBounds: () => stack.value?.getMaster().getViewBounds() ?? null,
});
</script>

<template>
  <div
    ref="containerRef"
    class="velo-plot-stacked"
    :class="props.class"
    role="img"
    :aria-label="ariaLabel ?? `Stacked chart with ${panes.length} panes`"
    :data-ready="isReady"
    :style="{
      position: 'relative',
      width: typeof width === 'number' ? `${width}px` : width,
      height: typeof height === 'number' ? `${height}px` : height,
    }"
  />
</template>

// src/svelte/StackedPlot.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { createStackedPlot } from "./useStackedPlot";
  import type { StackedChartOptions } from "../core/stacked";

  export let panes: StackedChartOptions["panes"];
  export let width: number | string = "100%";
  export let height: number | string = 480;
  export let stackOptions: Omit<StackedChartOptions, "container" | "panes"> = {};
  let className = "";
  export { className as class };

  const api = createStackedPlot({ panes, ...stackOptions });
  let container: HTMLDivElement;

  onMount(() => api.mount(container));
  onDestroy(() => api.unmount());

  $: api.sync({ panes, ...stackOptions });
</script>

<div
  bind:this={container}
  class={`velo-plot-stacked${className ? ` ${className}` : ""}`}
  role="img"
  style:position="relative"
  style:width={typeof width === "number" ? `${width}px` : width}
  style:height={typeof height === "number" ? `${height}px` : height}
/>
