// src/react/useStackedPlot.ts
/**
 * useStackedPlot - React hook for multi-pane stacked charts
 */

import {
  useEffect,
  useRef,
  useState,
  useCallback,
  type RefObject,
} from "react";
import type { StackedChart, StackedChartOptions } from "../core/stacked";
import type { Range } from "../types";
import {
  createRegisteredStackedChart,
  stackedStructureKey,
  syncStackedOptions,
  syncStackedPaneSeries,
} from "../bindings/shared";
import type { VeloPlotSeries } from "../bindings/shared";

export interface UseStackedPlotOptions
  extends Omit<StackedChartOptions, "container"> {}

export interface UseStackedPlotReturn {
  containerRef: RefObject<HTMLDivElement>;
  stack: StackedChart | null;
  isReady: boolean;
  fitAll: (options?: { x?: Range; padding?: number }) => void;
  resetAll: () => void;
}

export function useStackedPlot(
  options: UseStackedPlotOptions,
): UseStackedPlotReturn {
  const containerRef = useRef<HTMLDivElement>(null);
  const stackRef = useRef<StackedChart | null>(null);
  const destroyRef = useRef<(() => void) | null>(null);
  const [stack, setStack] = useState<StackedChart | null>(null);
  const [isReady, setIsReady] = useState(false);

  const optionsRef = useRef(options);
  const structureKeyRef = useRef(stackedStructureKey(options.panes));
  const paneSeriesRef = useRef(new Map<string, Map<string, VeloPlotSeries>>());
  optionsRef.current = options;

  const mountStack = useCallback(() => {
    const el = containerRef.current;
    if (!el) return;

    destroyRef.current?.();
    const created = createRegisteredStackedChart({
      ...optionsRef.current,
      container: el,
    });
    stackRef.current = created;
    destroyRef.current = () => {
      created.destroy();
      stackRef.current = null;
    };
    setStack(created);
    structureKeyRef.current = stackedStructureKey(optionsRef.current.panes);
    paneSeriesRef.current = syncStackedPaneSeries(
      created,
      optionsRef.current.panes,
      new Map(),
    );

    created.whenReady().then(() => setIsReady(true));
  }, []);

  useEffect(() => {
    mountStack();
    return () => {
      setIsReady(false);
      destroyRef.current?.();
      destroyRef.current = null;
      setStack(null);
    };
  }, [mountStack]);

  useEffect(() => {
    const current = stackRef.current;
    if (!current || !isReady) return;

    const nextKey = stackedStructureKey(options.panes);
    if (nextKey !== structureKeyRef.current) {
      mountStack();
      return;
    }

    syncStackedOptions(current, options);
    paneSeriesRef.current = syncStackedPaneSeries(
      current,
      options.panes,
      paneSeriesRef.current,
    );
  });

  const fitAll = useCallback((opts?: { x?: Range; padding?: number }) => {
    stackRef.current?.fitAll(opts);
  }, []);

  const resetAll = useCallback(() => {
    stackRef.current?.resetAll();
  }, []);

  return { containerRef, stack, isReady, fitAll, resetAll };
}

// src/solid/useStackedPlot.ts
import { createSignal, onCleanup } from "solid-js";
import type { StackedChart, StackedChartOptions } from "../core/stacked";
import type { Range } from "../types";
import { createRegisteredStackedChart, stackedStructureKey, syncStackedOptions, syncStackedPaneSeries } from "../bindings/shared";
import type { VeloPlotSeries } from "../bindings/shared";

export function useStackedPlot(getOptions: () => Omit<StackedChartOptions, "container">) {
  const [stack, setStack] = createSignal<StackedChart | null>(null);
  const [isReady, setIsReady] = createSignal(false);
  let destroy: (() => void) | null = null;
  let structureKey = "";
  let paneSeries = new Map<string, Map<string, VeloPlotSeries>>();

  const mount = (el: HTMLDivElement) => {
    destroy?.();
    const opts = getOptions();
    const created = createRegisteredStackedChart({ ...opts, container: el });
    setStack(created);
    destroy = () => created.destroy();
    structureKey = stackedStructureKey(opts.panes);
    paneSeries = syncStackedPaneSeries(created, opts.panes, new Map());
    created.whenReady().then(() => setIsReady(true));
  };

  const setContainerRef = (el: HTMLDivElement | null | undefined) => {
    if (el) mount(el);
  };

  onCleanup(() => {
    destroy?.();
    setStack(null);
    setIsReady(false);
  });

  return {
    setContainerRef,
    stack,
    isReady,
    fitAll: (opts?: { x?: Range; padding?: number }) => stack()?.fitAll(opts),
    resetAll: () => stack()?.resetAll(),
    sync: () => {
      const s = stack();
      const opts = getOptions();
      if (!s || !isReady()) return;
      const nextKey = stackedStructureKey(opts.panes);
      if (nextKey !== structureKey) {
        mount(s.container);
        return;
      }
      syncStackedOptions(s, opts);
      paneSeries = syncStackedPaneSeries(s, opts.panes, paneSeries);
    },
  };
}
